### PR TITLE
version updates for running on flutter 3.0.5

### PR DESCRIPTION
**Pull request by srihariash999**
Hey @SherlockHolmes2045  I made a few changes to manifest, build.gradle and updated a few dependencies' version to remove compile errors building with flutter 3.0.5.

Now the behaviour of the app is a bit strange. The app keeps closing when ran using `flutter run` but the actual flutter terminal is not disconnecting (which would indicate a crash), but the app just won't launch. I changed devices to check and emulators too. But couldn't determine what is happening.

Please have a look when you can. Any lead would be great! I wanted to make a manga reader with flutter myself. So if fanga gets to a stable point with flutter 3.0.5 I would be happy to use this as a starting point or add the features I'd like in this itslef rather than starting out from scratch. 

Thanks.

### CODE REVIEW

**Comment by srihariash999** [comment]
Hey @SherlockHolmes2045 did you get time to check this out?

**Comment by SherlockHolmes2045** [comment]
Hello , sorry it's now I'm viewing this notification. Will try to look at this this weekend,was very busy actually.

**Comment by srihariash999** [comment]
@SherlockHolmes2045 Sure, no worries. Hope you will get time this weekend.

**Comment by SherlockHolmes2045** [comment]
@srihariash999 finaly merged your pull request and put everything together on master. Thank for your help I'm definitely back with the development of this app

**Comment by srihariash999** [comment]
Hey @SherlockHolmes2045  great to see you back in developing Fanga.

I see a commit you made a few minutes ago haha, I just made those changes after syncing my fork's master with yours an hour or so ago. But one thing, the app not launching on emulator (didn't test on real device yet), remains, Although I can manually launch the app after the run now.

**Comment by SherlockHolmes2045** [comment]
Actually I'm not having this issue. If after syncing the issue persist just open an issue and I'll give a look at it.
I'm actually working on making the server up again

**Pull request merged**
